# https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md
openapi: 3.0.2
info:
  title: SAMPLE API
  license:
    name: MIT
  version: 1.0.0
servers:
  - url: '/api/v1'
paths:
  /test:
    post:
      tags:
        - test
      summary: 'test api'
      x-swagger-router-controller: test
      operationId: aTest
      requestBody:
        description: 'request body'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Body'
      parameters:
        - name: param a
          in: query
          description: param a
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: Success
          content:
            applicaiton/json:
              schema:
                $ref: '#/components/schemas/Success'
        # responses may fall through to errors
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Body:
      properties:
        sample:
          type: string

    Success:
      required:
        - message
      properties:
        message:
          type: string

    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string
